name: pro_z
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+7

environment:
  sdk: '>=3.0.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  intl: ^0.19.0
  flutter_screenutil: ^5.9.3
  video_player: ^2.8.7
  fluttertoast: ^8.2.6
  flutter_expandable_fab: ^2.0.0
  shared_preferences: ^2.2.3
  streaming_shared_preferences: ^2.0.0
  cloud_firestore: ^4.8.4
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^15.1.0+1
  flutter_easyloading: ^3.0.5
  flutter_spinkit: ^5.2.0
  http: ^1.1.0
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.0+1
  firebase_auth: ^4.7.2
  flutter_facebook_auth: ^6.0.1
  google_sign_in: ^6.1.4
  pinput: ^3.0.0
  badges: ^3.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
flutter:
  uses-material-design: true
  assets:
    - assets/images/


