name: pro_z
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+8

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.19.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  intl: ^0.18.1
  flutter_screenutil: ^5.9.0
  video_player: any
  fluttertoast: ^8.2.4
  flutter_expandable_fab: ^2.0.0
  shared_preferences: ^2.2.2
  streaming_shared_preferences: ^2.0.0
  firebase_messaging: ^14.7.16
  flutter_local_notifications: ^16.3.2
  flutter_easyloading: ^3.0.5
  flutter_spinkit: ^5.2.0
  http: any
  dio: ^5.4.1
  pretty_dio_logger: ^1.3.1
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  firebase_auth: ^4.17.5
  pinput: ^4.0.0
  cloud_firestore: ^4.15.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/