name: pro_z
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1+15

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.19.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  intl: ^0.18.1
  flutter_screenutil: ^5.9.0
  video_player: any
  fluttertoast: ^8.2.5
  flutter_expandable_fab: ^2.0.0
  shared_preferences: ^2.2.3
  streaming_shared_preferences: ^2.0.0
  firebase_messaging: ^15.0.3
  flutter_local_notifications: ^17.2.1+1
  flutter_easyloading: ^3.0.5
  flutter_spinkit: ^5.2.1
  http: any
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  firebase_auth: ^5.1.3
  pinput: ^4.0.0
  cloud_firestore: ^5.2.0
  path_provider: ^2.1.3
  firebase_core: ^3.3.0
  firebase_crashlytics: ^4.0.3
  cached_network_image: ^3.3.1
  skeletonizer: ^1.4.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
flutter:
  assets:
    - assets/images/
    - assets/PDF_file_icon.png