name: pro_z
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+7

environment:
  sdk: '>=3.0.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  get: ^4.6.6
  intl: ^0.18.1
  flutter_screenutil: ^5.9.3
  video_player: ^2.8.7
  fluttertoast: ^8.2.6
  flutter_expandable_fab: ^2.0.0
  shared_preferences: ^2.2.3
  streaming_shared_preferences: ^2.0.0
  cloud_firestore: ^5.0.1
  firebase_messaging: ^15.0.1
  flutter_local_notifications: ^17.1.2
  flutter_easyloading: ^3.0.5
  flutter_spinkit: ^5.2.1
  http: ^1.2.1
  dio: ^5.4.3
  pretty_dio_logger: ^1.3.1
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  firebase_auth: ^5.1.0
  flutter_facebook_auth: ^6.0.1
  google_sign_in: ^6.2.1
  pinput: ^5.0.0
  badges: ^3.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
flutter:
  uses-material-design: true
  assets:
    - assets/images/


