name: pro_z
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+7

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  intl: ^0.18.0
  flutter_screenutil: ^5.8.2
  video_player: any
  fluttertoast: ^8.2.2
  flutter_expandable_fab: ^1.8.0
  shared_preferences: ^2.1.1
  streaming_shared_preferences: ^2.0.0
  firebase_messaging: ^14.7.9
  flutter_local_notifications: ^14.1.0
  flutter_easyloading: ^3.0.5
  flutter_spinkit: ^5.2.0
  http: any
  dio: ^5.1.2
  pretty_dio_logger: ^1.3.1
  cookie_jar: ^4.0.2
  dio_cookie_manager: ^3.0.0
  firebase_auth: ^4.15.3
  pinput: ^2.2.31
  cloud_firestore: ^4.7.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/